# Force only Python provider
providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["python3 -m pip install -r src/backend/requirements.txt"]

[start]
cmd = "cd src/backend && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
